### ISSUE TITLE
error compiling ffmpeg

### ISSUE THREAD

**Issue by ericfrederich** [hiteshsondhi88/ffmpeg-android#5]
I got this error trying to build on Linux Mint (based on Ubuntu 14.04)

```
In file included from libavcodec/x86/mpegvideoenc.c:83:0:
libavcodec/x86/mpegvideoenc_template.c: In function 'dct_quantize_ssse3':
libavcodec/x86/mpegvideoenc_template.c:151:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
libavcodec/x86/mpegvideoenc_template.c:186:9: error: 'asm' operand has impossible constraints
         __asm__ volatile(
         ^
```
